1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np
print(np.__version__)

1.21.5


3. Create a null vector of size 10 (★☆☆)

In [3]:
import numpy as np

np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

4. How to find the memory size of any array (★☆☆)

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr.size * arr.itemsize)

20


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
arr = np.arange(11)
arr = arr[::-1]
print(arr)

[10  9  8  7  6  5  4  3  2  1  0]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)

In [17]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
arr = np.random.random((3,3))
print(arr)

[[0.41729157 0.8066976  0.25034664]
 [0.21143615 0.46983967 0.66895205]
 [0.67512391 0.98302322 0.39543798]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
arr = np.random.random((10,10))
arr_min = arr.min()
arr_max = arr.max()

print(arr_min, arr_max)

0.017175632796613716 0.995573865101351


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [24]:
#평균 구하기
arr = np.random.random(30)
arr_m = arr.mean()
print(arr_m)

0.49568096559338204


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [25]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)

1. 0 * np.nan
2. np.nan == np.nan
3. np.inf > np.nan
4. np.nan - np.nan
5. np.nan in set([np.nan])
6. 0.3 == 3 * 0.1

In [3]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
# 대각행렬 구하는 법
arr = np.diag(1+np.arange(4), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
arr = np.zeros((8,8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [11]:
# 넘파이에서는 unravel_index라는 함수를 이용해서 어떤 index를 인자로 넘겨받은 shape에 매핑되는 index를 반환받을 수 있다.

print(np.unravel_index((99),(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [13]:
# 넘파이 복사 붙여넣기
arr = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
# np.mean : 산술평균(평균) np.std = 표준편차
arr = np.random.random((5,5))
arr = (arr - np.mean(arr)) / (np.std(arr))
print(arr)

[[-0.72917686 -1.44568651 -1.61043584  0.04083895  0.91147312]
 [ 1.23210031  1.45435799  0.47123907  0.43385904 -0.49050391]
 [-0.37140682  1.03971109  1.30984058  0.12051415  0.94366939]
 [-0.78287527  1.50668702 -0.03423706 -0.2689164   0.64322539]
 [ 0.80274656 -1.19448125 -1.51881049 -1.38247641 -1.0812558 ]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [17]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [19]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
arr = np.arange(11)
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script? (★☆☆)

1. print(sum(range(5),-1))
2. from numpy import *
3. print(sum(range(5),-1))

In [22]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

1. Z**Z
2. 2 << Z >> 2
3. Z <- Z
4. 1j*Z
5. Z/1/1
6. Z<Z>Z

In [30]:
arr = np.array([[1,2,3]])
arr1 = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(arr**arr1)
print(2<<arr>>2)
print(arr<-arr)
print(1j*arr)
print(arr/1/1)
print(arr)

[[    1    32   729]
 [    1   256 19683]
 [    1     4    27]]
[[1 2 4]]
[[False False False]]
[[0.+1.j 0.+2.j 0.+3.j]]
[[1. 2. 3.]]
[[1 2 3]]


28. What are the result of the following expressions? (★☆☆)

1. np.array(0) / np.array(0)
2. np.array(0) // np.array(0)
3. np.array([np.nan]).astype(int).astype(float)

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\user\AppData\Local\Temp\ipykernel_18404\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_18404\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


29. How to round away from zero a float array ? (★☆☆)

In [38]:
# 균등 분포 정보를 생성하여 array에 만들기 np.uniform
# 첫 번째 array의 요소의 기호를 두 번째 array의 요소 기호로 바꿈 np.copysign
# 자신보다 크거나 같은 숫자 중 가장 정수로 변환해준다. np.ceil
# absolute value(절대값)을 반환해준다. np.abs
arr = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-2. -2. -5. -8.  2. -2. -6.  3. -3.  6.]


30. How to find common values between two arrays? (★☆☆)

In [47]:
# 두 개의 배열 x, y 의 교집합을 정렬하여 반환 np.intersect1d(x,y)
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1, arr2))

[1 2 3 4 7]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

32. Is the following expressions true? (★☆☆)

1. np.sqrt(-1) == np.emath.sqrt(-1)

In [48]:
# 어떤 수의 제곱근을 구해줍니다. np.sqrt()
# np.emath.sqrt함수는 음수가 들어가면 값이 복잡해집니다.
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\user\AppData\Local\Temp\ipykernel_18404\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
# np.datetime64('today') -> 오늘 날짜를 반환합니다.
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2023-01-13
