In [2]:
import numpy as np

Section 4. N차원 배열 정렬

4-1. 1차원 배열의 정렬

In [3]:
arr = np.random.randint(10, size=10)
print(arr)

[5 6 1 8 6 3 7 5 6 8]


In [6]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[1 3 5 5 6 6 6 7 8 8]
[8 8 7 6 6 6 5 5 3 1]


In [8]:
arr = np.sort(arr)
arr.sort()
print(arr)

[1 3 5 5 6 6 6 7 8 8]


4-2. 2차원 배열의 정렬

In [9]:
arr = np.random.randint(15, size=(3,4))
print(arr)

[[6 4 7 4]
 [1 9 2 1]
 [4 6 2 1]]


In [12]:
print(np.sort(arr, axis=None))

[1 1 1 2 2 4 4 4 6 6 7 9]


In [14]:
# argsort()
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0))

[[1 4 2 1]
 [4 6 2 1]
 [6 9 7 4]]
[[1 0 1 1]
 [2 2 2 2]
 [0 1 0 0]]
