34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [1]:
import numpy as np

arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [15]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) # 결과를 B에 저장합니다. [3,3,3]
np.divide(A,2, out=A) # A를 2로 나눈 결과를 A에 저장합니다. [0.5, 0.5, 0.5]
np.negative(A, out=A) # A에 -1을 곱한 결과를 A에 저장합니다. [-0.5, -0.5, -0.5]
np.multiply(A,B, out = A)
print(A)

[-1.5 -1.5 -1.5]


36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [17]:
arr = np.random.uniform(0,10,10) # 넘파이 균등분포 랜덤으로 만들기 (최소 0, 최대 10, 10개 생성)

# 넘파이 함수를 통해 정수부분만 추출하는 여러가지 방법
print(arr - arr%1)
print(arr // 1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[2. 2. 8. 5. 6. 2. 5. 5. 5. 3.]
[2. 2. 8. 5. 6. 2. 5. 5. 5. 3.]
[2. 2. 8. 5. 6. 2. 5. 5. 5. 3.]
[2 2 8 5 6 2 5 5 5 3]
[2. 2. 8. 5. 6. 2. 5. 5. 5. 3.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [3]:
import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [5]:
def integer():
    for x in range(10):
        yield x  # return 과 yield의 차이점은 모든 결과 값을 한번에 메모리에 올려놓는 return, 결과값을 하나씩 메모리에 올려놓는 yield.
                 # 성능 측면에서 yield가 상당히 좋다.
arr = np.fromiter(integer(), dtype=float, count=-1) # np.fromiter(순환할 수 있는 객체, 데이터 타입, 객체에서 읽어올 맴버의 개수)
                                                    # np.fromiter() 는 순환할 수 있는 구조를 가지는 데이터를 기반으로 1차원 배열을 생성
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
arr = np.linspace(0, 1, 11, endpoint=False)[1:] # np.linspace(시작점, 끝점, 숫자 개수, (끝점 포함,불포함)) 구간내 숫자를 채워주는 함수
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it (★★☆)

In [8]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.06012056 0.15221944 0.16410361 0.46747524 0.71813139 0.78163898
 0.84493667 0.89851459 0.94185961 0.96115687]


41. How to sum a small array faster than np.sum? (★★☆)

In [10]:
arr = np.array([1,2,3,4,5])
result = arr.sum(axis=None) # Python에서 기본적으로 제공하는 sum() 함수에 axis를 None으로 설정해주면 가장 빠르게 1차원 배열을 계산합니다.
print(result)

15


42. Consider two random array A and B, check if they are equal (★★☆)

In [4]:
arr1 = np.random.randint(0,2,5)
arr2 = np.random.randint(0,2,5)
#equal = np.array_equal(arr1, arr2) # np.array_equal 두개의 Numpy 배열이 같은 형상이고, 같은 원소들 값인지 확인.
equal = np.allclose(arr1, arr2) # 
print(equal)

False


np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=Flase) 는 a와 b가 근사적으로 값이 같은지 확인하는 함수입니다. 
rtol(상대 오차)는 절대값이 큰 값에 대해 상대적으로 허용되는 오차를 의미하며, atol은 절대값이 작은 값에 대해 절대적으로 허용되는 오차를 의미합니다.
equal_nan=True로 설정하면 Nan값도 같은 것으로 간주합니다.
이 함수는 a와 b의 shape가 같을 때 사용 가능합니다.

43. Make an array immutable (read-only) (★★☆)

In [9]:
arr = np.zeros(10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

불변 배열은 더 이상 값을 수정 할 수 없으며, 새로운 배열을 생성해야합니다.
배열을 불변으로 만드는 방법은 arr.flags.writeable 인자를 False로 설정하면 됩니다.
flags.writeable 는 배열의 값을 변경할 수 있는지 여부를 나타내는 값입니다.

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) *

In [13]:
arr = np.random.random((10,2))
x,y = arr[:,0], arr[:,1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
print(x)
print(y)

[0.82143532 0.91978513 0.7310624  0.57595957 0.56013412 0.86182254
 0.89210229 0.628206   0.98454772 0.78562837]
[0.06985364 0.87499413 0.16230932 0.8356887  0.38235694 0.55005658
 0.99494532 0.05025673 0.29341427 0.03367384]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
arr = np.random.random(10)
arr[arr.argmax()]=0 # arr.argmax()는 배열에서 가장 큰 값의 인덱스를 반환합니다. arr[arr.argmax()]=0은 배열에서 가장 큰 값을 0으로 바꿔줍니다.
print(arr)

[0.14453967 0.5019493  0.62018351 0.36910243 0.         0.775515
 0.28888488 0.17025507 0.1707542  0.11278934]


 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [22]:
arr = np.zeros((5,5),[('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


1. np.linspace(start, stop, num) 함수는 start부터 stop까지 num개의 수를 균일한 간격으로 배열을 만듭니다. 
2. np.meshgrid()는 주어진 배열을 x,y 2D 배열로 반환합니다. 

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [25]:
X = np.arange(8)
Y = X+0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


1. Cauchy행렬은 행렬 형태로 표현된 두 벡터의 각 원소들을 서로 나눈 값으로 구성된 행렬입니다. Cauchy 행렬은 행렬 C와 벡터 x, y를 포함하는 행렬이며, C(i, j) = x(i) / y(j) 입니다.
2. np.subtract.outer(x,y) 는 주어진 1D 배열 x와y의 원소들간의 차를 구하는 2D배열을 반환합니다.
3. np.linalg.det()는 주어진 2D배열의 행렬식을 구하는 함수입니다. 행렬식은 행렬의 크기와 방향성을 나타내는 스칼라 값입니다. 정사각 행렬에 대해서만 정의됩니다. 행렬식이 0이면 해당 행렬은 역행렬이 존재하지 않습니다.

48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [26]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


1. np.iinfo()는 정수 타입의 정보를 제공하며, np.finfo()는 부동 소수점 타입의 정보를 제공합니다. 
2. NumPy는 다음과 같은 스칼라 유형을 제공합니다.

    bool: 표현 가능한 최소값(False), 최대값(True)
    
    int: int8, int16, int32, int64. 표현 가능한 최소값과 최대값은 각각, -(2^(n-1)) ~ 2^(n-1) - 1 
    
    uint: uint8, uint16, uint32, uint64. 표현 가능한 최소값(0), 최대값(2^n - 1) 
    
    float: float16, float32, float64. 표현 가능한 최소값과 최대값은 각각, -(2^(n-1)) ~ 2^(n-1) - 1 /

49. How to print all the values of an array? (★★☆)

In [27]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((8,8))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


1. np.set_printoptions() 함수를 사용하면 출력하는 배열의 출력 옵션을 조정할 수 있습니다. 
2. np.set_printoptions(threshold=float("inf"))는 threshold를 무한대로 설정하여 모든 배열을 출력하도록 합니다.

50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [43]:
arr = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr-v)).argmin()
print(arr[index])

28


1. np.abs()는 절대값을 계산해줍니다. 
2. numpy.argmin()는 배열에서 최소값의 인덱스를 반환해줍니다.

51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) *

In [44]:
arr = np.zeros(10, [('position', [('x', float,1),('y', float,1)]), ('color', [('r', float,1),('g', float,1),('b', float,1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\user\AppData\Local\Temp\ipykernel_18544\4290018651.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(10, [('position', [('x', float,1),('y', float,1)]), ('color', [('r', float,1),('g', float,1),('b', float,1)])])


In [46]:
# This is created by openAI chatbot 
import numpy as np

# 구조체 타입 정의
dtype = np.dtype([('x', np.float32), ('y', np.float32),
                  ('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])

# 구조체 배열 생성
points = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)], dtype=dtype)

print(points)


[(1., 2., 3, 4,  5) (6., 7., 8, 9, 10)]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
arr = (np.random.rand(10)*100).astype(np.float32)
Y = arr.view(np.int32)
Y[:] = arr
print(Y)

[54 65  3 60 78 48 59 45 53 30]


1. arr.view()는 넘파이 배열을 특정 타입으로 변화하는 함수입니다. 이 함수는 원본 배열과 메모리를 공유하는 특성이 있으므로, view에 대한 변경은 원본 배열에도 영향을 줄 수 있습니다.

54. How to read the following file? (★★☆)

In [57]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')

arr = np.genfromtxt(s, delimiter=',', dtype=np.int)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\user\AppData\Local\Temp\ipykernel_18544\263650874.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.genfromtxt(s, delimiter=',', dtype=np.int)


1. np.genfromtxt() 함수는 텍스트 파일에서 데이터를 읽어 Numpy 배열로 변환하는 함수입니다. 이 함수는 텍스트 파일에서 데이터를 읽어 변환하며, 구분자(delimiter), 행 제목(header), 누락된 값 등을 지정할 수 있습니다.
2. StringIO는 파일을 읽고 쓰듯이 문자열도 읽고 쓰도록 해주는 클래스 입니다.

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [59]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


1. np.ndenumerate() 함수는 다차원 배열에서 인덱스와 그 인덱스에 해당하는 값을 함께 반환해주는 함수입니다.
2. np.ndindex() 함수는 N-dimensional 인덱스를 생성하는데 사용됩니다. 이 함수를 사용하면 N-dimensional 배열에서 각 요소에 대한 인덱스를 반복하면서 접근 할 수 있습니다.

56. Generate a generic 2D Gaussian-like array (★★☆) *

In [60]:
# This code is created by openAI chat bot
import numpy as np

mean = 0
std = 1
size = (3,3)
gaussian_array = np.random.normal(mean, std, size)
print(gaussian_array)

[[ 0.92420745 -0.42165904 -1.1846943 ]
 [ 0.27574227 -0.78763812 -0.24582559]
 [-2.05952084  2.15841334 -1.13592114]]


1. 가우시안 배열이란 가우시안 확률 분포를 따르는 랜덤 값으로 구성된 배열입니다. 가우시안 분포는 평균과 표준편차를 파라미터로 갖는 정규분포를 말합니다. Numpy에서는 numpy.random.normal(mean, std, size) 함수를 사용하여 가우시안 배열을 만들 수 있습니다. 

57. How to randomly place p elements in a 2D array? (★★☆)

In [63]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


np.put() 함수는 numpy 배열의 특정 인덱스에 값을 지정하는 함수입니다.

np.put(arr, indices, values)

arr : 값을 지정할 배열
indices : 지정할 인덱스
values : 지정할 값

np.random.choice(range(n*n), p, replace=False)는 nxn 크기의 범위를 갖는 0부터 n*n-1까지의 숫자들 중에서 p 개수만큼의 숫자를 랜덤하게 선택하며, 선택된 숫자들은 중복되지 않도록 합니다.

range(nn) : nn 크기의 범위를 갖는 0부터 n*n-1까지의 숫자들

p : 선택될 숫자의 개수

replace=False : 선택된 숫자들이 중복되지 않도록 합니다.

58. Subtract the mean of each row of a matrix (★★☆)

In [66]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.41098415 -0.21332866  0.1772788  -0.51565092  0.21421124  0.24482109
   0.13562389 -0.2429269   0.39556249  0.21539313]
 [ 0.38516246 -0.04050371  0.06816377  0.00783639  0.11441969  0.12938594
  -0.58384474  0.17844653  0.18588655 -0.44495289]
 [ 0.12039385  0.1278734  -0.43950266  0.39452119 -0.35039916  0.24730801
  -0.31048891  0.30348812  0.00589866 -0.09909249]
 [ 0.38519306 -0.39217035  0.25219671  0.14481527 -0.47026754  0.198558
   0.33452159 -0.00743072  0.06238171 -0.50779774]
 [ 0.28407421 -0.06197993  0.23197958  0.1469933  -0.38967439 -0.42122025
  -0.48282373  0.21319907  0.2189486   0.26050354]]


np.mean(axis=1)을 사용하여 각 행에 대한 평균을 구합니다.

X.mean(axis=1, keepdims=True)는 X 행렬의 각 행에 대한 평균을 구하는 것입니다.
axis=1 은 행 방향으로 평균을 구하는 것을 의미하며, keepdims=True는 결과 행렬의 차원을 원래와 동일하게 유지하도록 합니다. 즉, 각 행의 평균이 하나의 원소로 나타나는 행렬을 반환합니다.

59. How to sort an array by the nth column? (★★☆)

In [25]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[8 6 0]
 [8 8 2]
 [7 1 3]]
[[7 1 3]
 [8 6 0]
 [8 8 2]]


argsort() 함수는 각 원소들의 인덱스를 정렬한 결과를 반환하는 함수입니다. arr[:,1]의 모든 첫번째 열을 선택하여 그 열을 기준으로 sorting하여 반환하게 됩니다.

60. How to tell if a given 2D array has null columns? (★★☆)

In [42]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

False


(~arr.any(axis=0))은 arr 배열의 각 열에 값이 있는지 없는지에 대해 불리언 값을 반환합니다.

.any()를 붙이게 되면 그 불리언 배열에 하나라도 True가 있는지 없는지를 확인하는데, 이 경우에는 True가 있다면 그 행에는 최소 하나의 Null값이 있다는 뜻이고 False라면 그 행에는 Null값이 없다는 뜻입니다.

 61. Find the nearest value from a given value in an array (★★☆)

In [47]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.509551434074172


.flat은 배열을 1차원으로 펼칩니다. np.abs(Z - z)는 Z와 z의 차이를 절대값으로 반환합니다. 

argmin()은 최솟값의 인덱스를 반환합니다. 

그래서 Z.flat[np.abs(Z - z).argmin()]는 Z배열에서 z와 차이가 가장 작은 값을 가진 요소를 반환합니다.

62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3).reshape(1,3)
it = np.nditer([arr1,arr2,None])
for x,y,z in it:
    z[...] = x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


np.nditer 함수는 numpy의 다차원 배열을 순회할 수 있는 iterator를 만들어줍니다.



63. Create an array class that has a name attribute (★★☆) *