In [2]:
import numpy as np

Section 6. N차원 배열의 병합

6-1. 배열에 원소 추가 및 삭제

In [5]:
# python list
arr =[1,2,3,4,5,6,7,8]
arr.insert(2, 50)
print(arr)

# 1차원 배열
arr = np.arange(1,9)
arr = np.insert(arr, 2, 50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]
[ 1  2 50  3  4  5  6  7  8]


In [9]:
# 2차원 배열 
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr, 2, 50, axis=0)
arr = np.insert(arr, 2, 50, axis=1)
print(arr)

[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [50 50 50 50 50]
 [ 9 10 50 11 12]]


In [15]:
# delete()  ''' insert() 함수와 같이 axis값을 주지 않으면 1차원 배열로 변경해서 반환함'''
arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr, 2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  4  5  6  7  8  9 10 11 12]


6-2. 배열 간의 병합

In [21]:
# append()
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2, end="\n\n")

# axis=0
arr3 = np.append(arr1, arr2, axis=0)
print(arr3, end="\n\n")

# axis=1
arr3 = np.append(arr1, arr2, axis=1)
print(arr3, end="\n\n")

# axis값이 없으면 1차원으로 변경하여 반환함

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]



In [24]:
# vstack(), hstack()

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.vstack((arr1,arr2))
print(arr3)

arr3 = np.hstack((arr1,arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [3]:
# concatenate()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.concatenate([arr1,arr2], axis=1)
print(arr3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


6-3. 배열 분할

In [5]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
print(arr)

# vsplit() => axis=0
arr_vsplit = np.vsplit(arr, 3)
print(arr_vsplit)

# hsplit() => axis=1
arr_hsplit = np.hsplit(arr,2)
print(arr_hsplit)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [3]:
# 3차원 배열
arr = np.random.randint(0, 10, (4,6,8))
print(arr)

[[[5 3 5 3 4 6 4 7]
  [1 4 8 2 9 2 9 7]
  [1 3 2 8 6 3 7 3]
  [8 1 5 5 1 0 5 7]
  [6 0 9 6 3 8 2 3]
  [0 3 3 3 1 1 8 0]]

 [[5 9 0 8 2 1 9 2]
  [1 0 9 1 3 9 2 5]
  [5 3 3 2 7 2 7 2]
  [5 2 0 1 8 8 2 6]
  [9 0 2 9 7 1 0 7]
  [2 4 8 1 5 7 6 1]]

 [[7 3 8 8 9 7 7 8]
  [1 9 2 2 0 2 2 1]
  [6 1 8 0 9 6 4 9]
  [0 5 3 0 6 3 4 4]
  [0 5 4 5 9 9 8 2]
  [9 5 0 4 4 5 5 0]]

 [[9 3 2 8 6 4 1 8]
  [4 3 4 9 9 0 9 9]
  [0 3 9 6 0 1 6 2]
  [1 2 0 9 3 1 5 7]
  [0 2 8 3 7 3 5 0]
  [2 0 6 2 9 5 0 0]]]


In [10]:
arr_vsplit = np.vsplit(arr,2)
print(arr_vsplit)

[array([[[4, 1, 1, 0, 0, 3, 1, 1],
        [3, 5, 3, 3, 5, 3, 9, 4],
        [2, 8, 2, 8, 1, 4, 4, 1],
        [7, 0, 8, 3, 6, 9, 5, 0],
        [6, 6, 1, 8, 0, 0, 6, 3],
        [4, 7, 9, 7, 9, 8, 1, 8]],

       [[9, 0, 6, 4, 1, 3, 4, 1],
        [4, 0, 7, 9, 6, 3, 9, 5],
        [4, 3, 1, 2, 7, 8, 5, 0],
        [5, 0, 9, 0, 4, 3, 5, 8],
        [1, 0, 5, 2, 9, 7, 3, 4],
        [1, 0, 6, 9, 4, 6, 7, 9]]]), array([[[9, 2, 2, 9, 3, 6, 2, 5],
        [4, 7, 9, 2, 9, 2, 4, 6],
        [4, 4, 9, 3, 1, 5, 4, 1],
        [0, 2, 3, 1, 5, 5, 6, 2],
        [7, 8, 2, 4, 3, 5, 7, 4],
        [2, 4, 5, 7, 6, 4, 1, 2]],

       [[7, 0, 7, 1, 7, 7, 7, 9],
        [5, 1, 5, 4, 4, 0, 4, 5],
        [5, 3, 2, 3, 3, 2, 4, 0],
        [8, 8, 7, 7, 9, 9, 3, 1],
        [4, 0, 1, 4, 1, 0, 9, 0],
        [7, 6, 3, 0, 5, 7, 1, 4]]])]


In [5]:
arr_hsplit = np.hsplit(arr,2)
print(arr_hsplit)

[array([[[5, 3, 5, 3, 4, 6, 4, 7],
        [1, 4, 8, 2, 9, 2, 9, 7],
        [1, 3, 2, 8, 6, 3, 7, 3]],

       [[5, 9, 0, 8, 2, 1, 9, 2],
        [1, 0, 9, 1, 3, 9, 2, 5],
        [5, 3, 3, 2, 7, 2, 7, 2]],

       [[7, 3, 8, 8, 9, 7, 7, 8],
        [1, 9, 2, 2, 0, 2, 2, 1],
        [6, 1, 8, 0, 9, 6, 4, 9]],

       [[9, 3, 2, 8, 6, 4, 1, 8],
        [4, 3, 4, 9, 9, 0, 9, 9],
        [0, 3, 9, 6, 0, 1, 6, 2]]]), array([[[8, 1, 5, 5, 1, 0, 5, 7],
        [6, 0, 9, 6, 3, 8, 2, 3],
        [0, 3, 3, 3, 1, 1, 8, 0]],

       [[5, 2, 0, 1, 8, 8, 2, 6],
        [9, 0, 2, 9, 7, 1, 0, 7],
        [2, 4, 8, 1, 5, 7, 6, 1]],

       [[0, 5, 3, 0, 6, 3, 4, 4],
        [0, 5, 4, 5, 9, 9, 8, 2],
        [9, 5, 0, 4, 4, 5, 5, 0]],

       [[1, 2, 0, 9, 3, 1, 5, 7],
        [0, 2, 8, 3, 7, 3, 5, 0],
        [2, 0, 6, 2, 9, 5, 0, 0]]])]
