In [37]:
import numpy as np

Section 5. N차원 배열의 형태변경

5-1. 배열의 형태 변경1 : reshape()

In [7]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3,4))
print(arr, arr.ndim)

arr = arr.reshape((2,3,2))
print(arr, arr.ndim)

arr = arr.reshape((2,2,1,3))
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


5-1. 배열의 형태 변경2 : resize(), ravel()

In [24]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
arr.resize(3,4)  # 배열의 형태를 새로 만들어줌
print(arr)

arr = arr.ravel() # 배열의 형태를 1차원으로 다시 만듦
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
arr = np.arange(1, 13)
print(arr)

arr = arr.reshape(3, -1) # -1을 넣으면 컴퓨터가 자동으로 계산하여 4를 넣어줌
print(arr)

arr = arr.reshape(3,2,-1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


5-3. 배열의 형태 변경3: expand_dims(), squeeze()

In [21]:
# expand_dims()  하나의 차원을 생성
arr = np.array([1,2])
print(arr, arr.shape) 

arr = np.expand_dims(arr, axis=1)
print(arr, arr.shape)

[1 2] (2,)
[[1]
 [2]] (2, 1)


In [36]:
# squeeze() 하나의 차원을 축소
arr = np.array([[1,2]])
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

arr = np.array([[[1],
                 [2],
                 [3]]])
arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)

arr = np.array([[[1,2,3]]])
print(arr, arr.shape, arr.ndim)
arr = np.squeeze(arr)
print(arr, arr.shape, arr.ndim)

[[1 2]] (1, 2) 2
[1 2] (2,) 1
[[1]
 [2]
 [3]] (3, 1) 2
[[[1 2 3]]] (1, 1, 3) 3
[1 2 3] (3,) 1


5-4. 전치행렬(Transopse)

In [40]:
arr = np.array([[1,2],
                 [3,4]])
print(arr.T)

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr.T)

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [42]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(arr.T)

arr2 = np.full((3,2),2)

print((arr.T).dot(arr2))

[[1 3 5]
 [2 4 6]]
[[18 18]
 [24 24]]
